- name: Run FastAPI
  block: 
  - name: Create systemd service file
    ansible.builtin.template:
      src: python-app.service.j2
      dest: "/etc/systemd/system/{{ project_name }}.service"
    notify: reload systemd and start

  - name: Ensure app is started
    ansible.builtin.systemd:
      name: "{{ project_name }}"
      state: started
      enabled: yes
      daemon_reload: yes
    changed_when: false
    
  - name: FastAPI deployment as successful
    ansible.builtin.set_fact:
      deployment_successful: true
      current_method: "default"
  when:
    - not deployment_successful    
    - framework == "fastapi"
  
- name: Run Dajango
  block: 
  - name: Create systemd service file
    ansible.builtin.template:
      src: python-app.service.j2
      dest: "/etc/systemd/system/{{ project_name }}.service"
    notify: reload systemd and start

  - name: Ensure app is started
    ansible.builtin.systemd:
      name: "{{ project_name }}"
      state: started
      enabled: yes
      daemon_reload: yes
    changed_when: false

  - name: Django deployment as successful
    ansible.builtin.set_fact:
      deployment_successful: true
      current_method: "default"
  when: 
    - not deployment_successful     
    - framework == "django" 